ALTER TABLE "VideoJob" ADD COLUMN IF NOT EXISTS "durationSeconds" INTEGER;
ALTER TABLE "VideoJob" ADD COLUMN IF NOT EXISTS "clipCount" INTEGER;
ALTER TABLE "VideoJob" ADD COLUMN IF NOT EXISTS "model" TEXT;
ALTER TABLE "VideoJob" ADD COLUMN IF NOT EXISTS "input" JSONB;
